### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by jihax54** [FabricMC/weave#4]
I want to use weave for merging client and server jar but there is no command? How to use. Help please, thanks.

**Comment by liach** [comment]
Weave is now dead. Use stitch
https://maven.fabricmc.net/net/fabricmc/stitch/0.4.3.71/stitch-0.4.3.71-all.jar
And in command line, run
```
java -jar stitch-0.4.3.71-all.jar mergeJar <client-jar> <server-jar> <output>
```
see https://github.com/FabricMC/stitch/blob/57b0e7fe30e4d7768b26f610385434771e90aad3/src/main/java/net/fabricmc/stitch/commands/CommandMergeJar.java#L36

**Comment by liach** [comment]
Or you can just clone https://github.com/FabricMC/yarn switch to the version you'd like and run `./gradlew mergeJars`

**Comment by jihax54** [comment]
Thank you!
